-- 1. Creamos la tabla desde cero
CREATE TABLE CRYPTO_DASHBOARD (
    id_registro      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo           VARCHAR2(50) DEFAULT 'Bitcoin (BTC)',
    precio_usd       NUMBER(15,2),
    volumen_24h      NUMBER(20,2),
    fecha_registro   DATE
);